packages:
  - '.'
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
minimumReleaseAgeExclude:
  - '@testing-library/user-event@14.6.4 || 14.6.5'
  - smol-toml@1.8.0
  - '@biomejs/biome@2.5.9'
  - '@biomejs/cli-darwin-arm64@2.5.9'
  - '@biomejs/cli-darwin-x64@2.5.9'
  - '@biomejs/cli-linux-arm64-musl@2.5.9'
  - '@biomejs/cli-linux-arm64@2.5.9'
  - '@biomejs/cli-linux-x64-musl@2.5.9'
  - '@biomejs/cli-linux-x64@2.5.9'
  - '@biomejs/cli-win32-arm64@2.5.9'
  - '@biomejs/cli-win32-x64@2.5.9'
  - '@tanstack/react-virtual@3.14.10'
  - '@tanstack/virtual-core@3.17.8'
overrides:
  serialize-javascript: '^7.0.5'
  diff: '^8.0.3'
